# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-10-30T12:20:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class FamilyListResponse(BaseModel):
    status: Optional[int] = None
    familyIds: Optional[List[int]] = None


class FamilyPerson(BaseModel):
    personId: int
    name: str


class FamilyResponse(BaseModel):
    status: Optional[int] = None
    familyId: int
    members: List[FamilyPerson]
