[project]
name = "rr-ct-board"
description = ""
authors = [
    {name = "Stefan Bund",email = "stefan@j32.de"}
]
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "connexion[swagger-ui,uvicorn] (>=3.3.0,<4.0.0)",
]
dynamic = ["version"]

[dependency-groups]
dev = [
    "datamodel-code-generator (>=0.35.0,<0.36.0)",
    "pytest (>=8.4.2,<9.0.0)",
    "pytest-mypy (>=1.0.1,<2.0.0)",
    "black (>=25.9.0,<26.0.0)",
    "pytest-black (>=0.6.0,<0.7.0)",
    "pytest-flake8 (>=1.3.0,<2.0.0)",
    "flake8-pyproject (>=1.2.3,<2.0.0)",
    "openapi-python-client (>=0.27.0,<0.28.0)"
]

[tool.poetry]
include = [ "ctclient", "rr_ct_board" ]
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
format = "{base}.{distance}"

[tool.poetry.scripts]
rr-ct-board = "rr_ct_board.app:main"

[tool.mypy]

[tool.pytest.ini_options]
addopts = "--black --flake8 --mypy"

[tool.black]
line-length = 96
include = ".py$"

[tool.flake8]
max-line-length = 96

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
