[project]
name = "rr-ct-board"
description = ""
authors = [
    {name = "Stefan Bund",email = "stefan@j32.de"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]
dynamic = ["version"]

[tool.poetry]
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry-dynamic-versioning]
enable = true
format = "{base}.{distance}"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"
