from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..models.device_type import DeviceType
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.device_meta import DeviceMeta


T = TypeVar("T", bound="Device")


@_attrs_define
class Device:
    """A device can be a smartphone or tablet running the ChurchTools app.

    Attributes:
        app_version (None | str): Used App Version Example: 0.9.0.
        device_id (str): Unique ID generated by the App Example: cf1gGE_oBhM:APA91bFUCyqIpB70ufPXJFsbEZZfQxSlYUZ3CcIzjkW
            2elRjJZ9g4tQfK3i_q8CJN1lhfSwdbtJG6bHo22_-Hwcy8JEpwWV9NNNDQUjdVgWimGk7Z5OAKjNryaYorbkRfYC1xSBjiGgF.
        meta (DeviceMeta):  Example: {'createdDate': '2020-01-01T00:00:00Z', 'createdPerson': {'id': 1}, 'modifiedDate':
            '2020-01-01T00:00:00Z', 'modifiedPerson': {'id': 1}}.
        person_id (int):  Example: 1.
        push_id (None | str): Push ID generated by Firebase Example: cf1gGE_oBhM:APA91bFUCyqIpB70ufPXJFsbEZZfQxSlYUZ3CcI
            zjkW2elRjJZ9g4tQfK3i_q8CJN1lhfSwdbtJG6bHo22_-Hwcy8JEpwWV9NNNDQUjdVgWimGk7Z5OAKjNryaYorbkRfYC1xSBjiGgF.
        ttl (datetime.datetime): Time To Live of Device Example: 2020-05-07T13:24:35+02:00.
        type_ (DeviceType): Device Type Example: FCM.
        created_at (Any | Unset): Use meta.createdDate instead
        id (Any | Unset): Use `deviceId` instead
        updated_at (Any | Unset): Use meta.modifiedDate instead
        version (Any | Unset): Use `appVersion` instead
    """

    app_version: None | str
    device_id: str
    meta: DeviceMeta
    person_id: int
    push_id: None | str
    ttl: datetime.datetime
    type_: DeviceType
    created_at: Any | Unset = UNSET
    id: Any | Unset = UNSET
    updated_at: Any | Unset = UNSET
    version: Any | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        app_version: None | str
        app_version = self.app_version

        device_id = self.device_id

        meta = self.meta.to_dict()

        person_id = self.person_id

        push_id: None | str
        push_id = self.push_id

        ttl = self.ttl.isoformat()

        type_ = self.type_.value

        created_at = self.created_at

        id = self.id

        updated_at = self.updated_at

        version = self.version

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "appVersion": app_version,
                "deviceId": device_id,
                "meta": meta,
                "personId": person_id,
                "pushId": push_id,
                "ttl": ttl,
                "type": type_,
            }
        )
        if created_at is not UNSET:
            field_dict["createdAt"] = created_at
        if id is not UNSET:
            field_dict["id"] = id
        if updated_at is not UNSET:
            field_dict["updatedAt"] = updated_at
        if version is not UNSET:
            field_dict["version"] = version

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.device_meta import DeviceMeta

        d = dict(src_dict)

        def _parse_app_version(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        app_version = _parse_app_version(d.pop("appVersion"))

        device_id = d.pop("deviceId")

        meta = DeviceMeta.from_dict(d.pop("meta"))

        person_id = d.pop("personId")

        def _parse_push_id(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        push_id = _parse_push_id(d.pop("pushId"))

        ttl = isoparse(d.pop("ttl"))

        type_ = DeviceType(d.pop("type"))

        created_at = d.pop("createdAt", UNSET)

        id = d.pop("id", UNSET)

        updated_at = d.pop("updatedAt", UNSET)

        version = d.pop("version", UNSET)

        device = cls(
            app_version=app_version,
            device_id=device_id,
            meta=meta,
            person_id=person_id,
            push_id=push_id,
            ttl=ttl,
            type_=type_,
            created_at=created_at,
            id=id,
            updated_at=updated_at,
            version=version,
        )

        device.additional_properties = d
        return device

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
